version: 2

jobs:
  "python-2.7": &test-template
    docker:
      - image: circleci/python:2.7-stretch-node-browsers
        environment:
          PERCY_PARALLEL_TOTAL: 4

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "dev-requirements.txt" }}

      - run:
          name: Install dependencies
          command: |
              sudo pip install virtualenv --upgrade
              python -m venv venv || virtualenv venv
              . venv/bin/activate
              pip install -r dev-requirements.txt
              npm install

      - run:
          name: Build
          command: npm run build-prod

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "dev-requirements.txt" }}
          paths:
              - "venv"
              - "node_modules"

      - run:
          name: Run lint
          command: |
              pylint dash_renderer setup.py
              flake8 dash_renderer setup.py

      - run:
          name: Run tests
          command: |
              . venv/bin/activate
              npm run test
              python --version
              python -m unittest tests.test_render.Tests
              python -m unittest tests.test_race_conditions.Tests

  "python-3.6":
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-node-browsers
        environment:
            PERCY_PARALLEL_TOTAL: 4


workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.6"